#-------------------------------------------------
# Make file for the application
#
# @author: Wild boar
#-------------------------------------------------

all:
	Rscript -e "rmarkdown::render('article.rmd', output_dir='_site')"

clean:
	rm -r _site