---
title: "Experiment 1: Simple Shape Detection"
date: "`r Sys.Date()`"
author: WildBoar
bibliography: article.bib
csl: ieee.csl
link-citations: true
output:
    rmdformats::readthedown:
    toc: 2
    highlight: tango
    mathjax: default
    number_sections: false
    fig_caption: true
---

## Introduction ##

### What ###

Convolutional filters and correlation have a symmetrical relationship mathematically. Therefore I hypothesize that an image of even-sized and spaced shapes of different types can be correctly classified using convolution. I also hypothesize that the filters will appear to have similar patterns as the matching shapes. Finally, I hypothesize that adding rotation to the conditions will generate exciting ways in the convolution filter.  

### Why ###

The primary purposes of this experiment are the following:

* I want to verify that I can use _Genetic Algorithms_ (GA) to generate useful convolutional filters.
* I want to verify my intuition about convolutional filters.
* I want to experiment with convolutional filter refinement.
* I am interested to see what happens when dealing with rotation.

### How ###

I aim to create a _generic_ GA that can compute using sequences of integers (which I am calling **DNA** sequences). I aim to specialize this algorithm to real problems by writing wrappers capable of mapping DNA sequences to solution formulations that make sense to the issue. Using genetic algorithms to create filters is an old idea [@etter1982recursive]. However, I plan to reprise the approach in this work to generate convolution filters.

Once I have used my generic algorithm to generate filters that give acceptable performance, my next idea is to experiment with various approaches to refine these algorithms using gradient descent approaches. I am particularly interested in comparing _traditional gradient descent_ with random refinement approaches and Adam [@kingma2014adam].


## Methodology ##

## Experiment ##

## Result ##

## Conclusion ##

## Future Work ##

## References ##

<div id="refs"></div>